### PR TITLE
go.mod: switch to github.com/mdlayher/packet@v1.0.0

### PR DESCRIPTION
**Pull request by mdlayher**
Signed-off-by: Matt Layher <mdlayher@gmail.com>

Make use of the Linux-only, non-deprecated package. Thanks again for gokrazy!

### CODE REVIEW

**Comment by stapelberg** [comment]
This breaks DHCP on the Raspberry Pi 4 for me :-/

**Comment by stapelberg** [comment]
This is the error message I’m seeing:
```
1970/01/01 01:02:47 gokrazy: attempt 148, starting ["/gokrazy/dhcp"]
1970/01/01 01:02:47 dhcp.go:308: write packet dc:a6:32:03:31:d1: sendto: invalid argument
1970/01/01 01:02:47 gokrazy: exit status 1
```

**Comment by stapelberg** [comment]
Here’s the strace output:
```
[…]
[pid  6124] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid  6123] <... uname resumed> {sysname="Linux", nodename="gokrazy", release="5.16.2", version="#1 SMP PREEMPT Wed Mar 1 20:57:29 UTC 2017", machine="aarch64", domainname="(none)"}) = 0
[pid  6123] socket(AF_NETLINK, SOCK_RAW|SOCK_CLOEXEC, NETLINK_ROUTE <unfinished ...>
[pid  6124] <... nanosleep resumed> NULL) = 0
[pid  6124] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid  6123] <... socket resumed> )      = 3<socket:[11576]>
[pid  6124] <... nanosleep resumed> NULL) = 0
[pid  6123] bind(3<socket:[11576]>, {sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, 12 <unfinished ...>
[pid  6124] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid  6123] <... bind resumed> )        = 0
[pid  6123] sendto(3<socket:[11576]>, {{len=17, type=0x12 /* NLMSG_??? */, flags=NLM_F_REQUEST|0x300, seq=1, pid=0}, "\x00"}, 17, 0, {sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, 12 <unfinished ...>
[pid  6124] <... nanosleep resumed> NULL) = 0
[pid  6124] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid  6123] <... sendto resumed> )      = 17
[pid  6124] <... nanosleep resumed> NULL) = 0
[pid  6124] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid  6123] getsockname(3<socket:[11576]>,  <unfinished ...>
[pid  6124] <... nanosleep resumed> NULL) = 0
[pid  6124] getpid()                    = 6123
[pid  6123] <... getsockname resumed> {sa_family=AF_NETLINK, nl_pid=6123, nl_groups=00000000}, [112->12]) = 0
[pid  6124] tgkill(6123, 6123, SIGURG)  = 0
[pid  6123] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=6123, si_uid=0} ---
[pid  6124] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid  6123] rt_sigreturn({mask=[]})     = 0
[pid  6124] <... nanosleep resumed> NULL) = 0
[pid  6124] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid  6123] recvfrom(3<socket:[11576]>,  <unfinished ...>
[pid  6124] <... nanosleep resumed> NULL) = 0
[pid  6124] nanosleep({tv_sec=0, tv_nsec=40000}, NULL) = 0
[pid  6124] nanosleep({tv_sec=0, tv_nsec=80000}, NULL) = 0
[pid  6124] nanosleep({tv_sec=0, tv_nsec=160000}, NULL) = 0
[pid  6124] nanosleep({tv_sec=0, tv_nsec=320000},  <unfinished ...>
[pid  6123] <... recvfrom resumed> [{{len=1344, type=0x10 /* NLMSG_??? */, flags=NLM_F_MULTI, seq=1, pid=6123}, "\x00\x00\x04\x03\x01\x00\x00\x00\x49\x00\x01\x00\x00\x00\x00\x00\x07\x00\x03\x00\x6c\x6f\x00\x00\x08\x00\x0d\x00\xe8\x03\x00\x00"...}, {{len=1404, type=0x10 /* NLMSG_??? */, flags=NLM_F_MULTI, seq=1, pid=6123}, "\x00\x00\x01\x00\x02\x00\x00\x00\x43\x10\x01\x00\x00\x00\x00\x00\x09\x00\x03\x00\x65\x74\x68\x30\x00\x00\x00\x00\x08\x00\x0d\x00"...}], 4096, 0, {sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, [112->12]) = 2748
[pid  6124] <... nanosleep resumed> NULL) = 0
[pid  6123] recvfrom(3<socket:[11576]>, {{len=20, type=NLMSG_DONE, flags=NLM_F_MULTI, seq=1, pid=6123}, 0}, 4096, 0, {sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, [112->12]) = 20
[pid  6124] nanosleep({tv_sec=0, tv_nsec=640000},  <unfinished ...>
[pid  6123] close(3<socket:[11576]>)    = 0
[pid  6123] socket(AF_INET, SOCK_DGRAM, IPPROTO_IP) = 3<socket:[11578]>
[pid  6123] ioctl(3<socket:[11578]>, SIOCGIFFLAGS, {ifr_name="eth0", ifr_flags=IFF_UP|IFF_BROADCAST|IFF_RUNNING|IFF_MULTICAST}) = 0
[pid  6123] ioctl(3<socket:[11578]>, SIOCSIFFLAGS, {ifr_name="eth0", ifr_flags=IFF_UP|IFF_BROADCAST|IFF_RUNNING|IFF_MULTICAST}) = 0
[pid  6124] <... nanosleep resumed> NULL) = 0
[pid  6123] openat(AT_FDCWD, "/sys/class/net/eth0/carrier", O_RDONLY|O_CLOEXEC <unfinished ...>
[pid  6124] nanosleep({tv_sec=0, tv_nsec=1280000},  <unfinished ...>
[pid  6123] <... openat resumed> )      = 4</sys/devices/platform/scb/fd580000.ethernet/net/eth0/carrier>
[pid  6123] epoll_create1(EPOLL_CLOEXEC) = 5<anon_inode:[eventpoll]>
[pid  6123] pipe2([6<pipe:[13372]>, 7<pipe:[13372]>], O_NONBLOCK|O_CLOEXEC) = 0
[pid  6123] epoll_ctl(5<anon_inode:[eventpoll]>, EPOLL_CTL_ADD, 6<pipe:[13372]>, {EPOLLIN, {u32=8874824, u64=8874824}}) = 0
[pid  6123] epoll_ctl(5<anon_inode:[eventpoll]>, EPOLL_CTL_ADD, 4</sys/devices/platform/scb/fd580000.ethernet/net/eth0/carrier>, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=1851647752, u64=281472533391112}}) = 0
[pid  6123] fcntl(4</sys/devices/platform/scb/fd580000.ethernet/net/eth0/carrier>, F_GETFL) = 0x20000 (flags O_RDONLY|O_LARGEFILE)
[pid  6123] fcntl(4</sys/devices/platform/scb/fd580000.ethernet/net/eth0/carrier>, F_SETFL, O_RDONLY|O_NONBLOCK|O_LARGEFILE) = 0
[pid  6123] fstat(4</sys/devices/platform/scb/fd580000.ethernet/net/eth0/carrier>, {st_dev=makedev(0, 24), st_ino=17165, st_mode=S_IFREG|0644, st_nlink=1, st_uid=0, st_gid=0, st_blksize=4096, st_blocks=0, st_size=4096, st_atime=8 /* 1970-01-01T01:00:08.399999995+0100 */, st_atime_nsec=399999995, st_mtime=8 /* 1970-01-01T01:00:08.399999995+0100 */, st_mtime_nsec=399999995, st_ctime=8 /* 1970-01-01T01:00:08.399999995+0100 */, st_ctime_nsec=399999995}) = 0
[pid  6124] <... nanosleep resumed> NULL) = 0
[pid  6123] read(4</sys/devices/platform/scb/fd580000.ethernet/net/eth0/carrier>,  <unfinished ...>
[pid  6124] epoll_pwait(5<anon_inode:[eventpoll]>,  <unfinished ...>
[pid  6123] <... read resumed> "1\n", 4097) = 2
[pid  6124] <... epoll_pwait resumed> [{EPOLLIN|EPOLLOUT, {u32=1851647752, u64=281472533391112}}], 128, 0, NULL, 1) = 1
[pid  6124] nanosleep({tv_sec=0, tv_nsec=2560000},  <unfinished ...>
[pid  6123] read(4</sys/devices/platform/scb/fd580000.ethernet/net/eth0/carrier>, "", 4095) = 0
[pid  6123] epoll_ctl(5<anon_inode:[eventpoll]>, EPOLL_CTL_DEL, 4</sys/devices/platform/scb/fd580000.ethernet/net/eth0/carrier>, 0x40001f5928) = 0
[pid  6123] close(4</sys/devices/platform/scb/fd580000.ethernet/net/eth0/carrier>) = 0
[pid  6123] socket(AF_PACKET, SOCK_DGRAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 4<socket:[11579]>
[pid  6123] fcntl(4<socket:[11579]>, F_GETFL) = 0x802 (flags O_RDWR|O_NONBLOCK)
[pid  6123] fcntl(4<socket:[11579]>, F_SETFL, O_RDWR|O_NONBLOCK) = 0
[pid  6123] fcntl(4<socket:[11579]>, F_GETFL) = 0x802 (flags O_RDWR|O_NONBLOCK)
[pid  6123] epoll_ctl(5<anon_inode:[eventpoll]>, EPOLL_CTL_ADD, 4<socket:[11579]>, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=1851647752, u64=281472533391112}}) = 0
[pid  6123] fcntl(4<socket:[11579]>, F_GETFL) = 0x802 (flags O_RDWR|O_NONBLOCK)
[pid  6123] fcntl(4<socket:[11579]>, F_SETFL, O_RDWR|O_NONBLOCK) = 0
[pid  6123] bind(4<socket:[11579]>, {sa_family=AF_PACKET, sll_protocol=htons(ETH_P_IP), sll_ifindex=if_nametoindex("eth0"), sll_hatype=ARPHRD_NETROM, sll_pkttype=PACKET_HOST, sll_halen=0}, 20) = 0
[pid  6123] getsockname(4<socket:[11579]>, {sa_family=AF_PACKET, sa_data="\10\0\2\0\0\0\1\0\0\6\334\2462\0031\321"}, [112->18]) = 0
[pid  6123] openat(AT_FDCWD, "/etc/localtime", O_RDONLY) = 8</etc/localtime>
[pid  6123] read(8</etc/localtime>,  <unfinished ...>
[pid  6124] <... nanosleep resumed> NULL) = 0
[pid  6124] nanosleep({tv_sec=0, tv_nsec=5120000},  <unfinished ...>
[pid  6123] <... read resumed> "TZif2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\5\0\0\0\5\0\0\0\0"..., 4096) = 1909
[pid  6123] read(8</etc/localtime>, "", 4096) = 0
[pid  6123] close(8</etc/localtime>)    = 0
[pid  6123] write(2</dev/pts/0>, "1970/01/01 01:05:27 dhcp.go:308:"..., 901970/01/01 01:05:27 dhcp.go:308: write packet dc:a6:32:03:31:d1: sendto: invalid argument
) = 90
[pid  6123] exit_group(1)               = ?
[pid  6127] <... futex resumed>)        = ?
[pid  6126] <... futex resumed>)        = ?
[pid  6125] <... futex resumed>)        = ?
[pid  6124] <... nanosleep resumed> <unfinished ...>) = ?
[pid  6125] +++ exited with 1 +++
[pid  6127] +++ exited with 1 +++
[pid  6126] +++ exited with 1 +++
[pid  6124] +++ exited with 1 +++
+++ exited with 1 +++
```

**Comment by mdlayher** [comment]
I'll check it out!

**Comment by mdlayher** [comment]
Ah, it appears there's a function in rtr7/dhcp4 that takes a net.PacketConn as a parameter but passes a raw.Addr to the net.PacketConn directly. So that needs to be updated first. On it.

**Comment by mdlayher** [comment]
Will pull in that commit after merge.

**Comment by mdlayher** [comment]
@stapelberg okay, with the new rtr7/dhcp4 I believe this should work for normal gokrazy Pis. I think I'll have to pull in this update to rtr7/router7 to fix things up there, but I'm working on it!

**Comment by stapelberg** [comment]
Yep, this seems to work fine now on a Raspberry Pi 4 :)

**Pull request merged**
